CREATE TABLE IF NOT EXISTS StudentInfo(
	keyid                              bigint(20)           NOT NULL AUTO_INCREMENT                COMMENT '主键',
	userid                             bigint(20)           NOT NULL DEFAULT 0                     COMMENT '用户id',
	studentid                          varchar(26)          NOT NULL DEFAULT ''                    COMMENT '学生ID:hash分表',
	studentname                        varchar(20)          NOT NULL DEFAULT ''                    COMMENT '学生姓名',
	sex                                tinyint(2) unsigned  NOT NULL DEFAULT 0                     COMMENT '性别(1:男 2:女)',
	birthday                           date                 NOT NULL DEFAULT '1900-01-01'          COMMENT '出生日期',
	phoneno                            varchar(20)          NOT NULL DEFAULT ''                    COMMENT '手机号码',
	wechat                             varchar(50)          NOT NULL DEFAULT ''                    COMMENT '微信号',
	email                              varchar(50)          NOT NULL DEFAULT ''                    COMMENT '邮箱',
	provinceid                         varchar(26)          NOT NULL DEFAULT ''                    COMMENT '省ID',
	provincename                       varchar(20)          NOT NULL DEFAULT ''                    COMMENT '省名称',
	cityid                             varchar(26)          NOT NULL DEFAULT ''                    COMMENT '城市ID',
	cityname                           varchar(20)          NOT NULL DEFAULT ''                    COMMENT '城市名称',
	districtid                         varchar(26)          NOT NULL DEFAULT ''                    COMMENT '区县ID',
	districtname                       varchar(20)          NOT NULL DEFAULT ''                    COMMENT '区县名称',
	address                            varchar(200)         NOT NULL DEFAULT ''                    COMMENT '详细地址',
	photopath                          varchar(100)         NOT NULL DEFAULT ''                    COMMENT '照片路劲',
	adviserid                          varchar(26)          NOT NULL DEFAULT ''                    COMMENT '顾问ID',
	advisername                        varchar(26)          NOT NULL DEFAULT ''                    COMMENT '顾问Name',
	campusid                           varchar(26)          NOT NULL DEFAULT ''                    COMMENT '校区ID',
	campusname                         varchar(50)          NOT NULL DEFAULT ''                    COMMENT '校区名称',
	schoolid                           varchar(26)          NOT NULL DEFAULT ''                    COMMENT '学校ID',
	schoolname                         varchar(50)          NOT NULL DEFAULT ''                    COMMENT '学校名称',
	haveclass                          tinyint(2) unsigned  NOT NULL DEFAULT 0                     COMMENT '是否上课:目前是否在我校上课 0、没有，1、有',
	existingclass                      varchar(50)          NOT NULL DEFAULT ''                    COMMENT '现课程',
	historyclass                       varchar(100)         NOT NULL DEFAULT ''                    COMMENT '历史课程',
	teacher                            varchar(50)          NOT NULL DEFAULT ''                    COMMENT '代课老师',
	chooseclass                        varchar(50)          NOT NULL DEFAULT ''                    COMMENT '选报课程',
	attendance                         decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '出勤率',
	remarks                            varchar(500)         NOT NULL DEFAULT ''                    COMMENT '课堂表现',
	firstsubject1                      decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '第一次模考科目一',
	firstsubject2                      decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '第一次模考科目二',
	firstsubject3                      decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '第一次模考科目三',
	secondsubject1                     decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '第二次模考科目一',
	secondsubject2                     decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '第二次模考科目二',
	secondsubject3                     decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '第二次模考科目三',
	thirdsubject1                      decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '第三次模考科目一',
	thirdsubject2                      decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '第三次模考科目二',
	thirdsubject3                      decimal(10,6)        NOT NULL DEFAULT 0                     COMMENT '第三次模考科目三',
	addtime                            datetime             NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '添加时间',
	modifytime                         timestamp            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间(CURRENT_TIMESTAMP)',
	isdelete                           tinyint(4) unsigned  NOT NULL DEFAULT 0                     COMMENT '删除标识:是否删除  0、没删除，1、删除',
	PRIMARY KEY (keyid),
	INDEX IDX_StudentInfo_1 (userid),
	INDEX IDX_StudentInfo_2 (studentid),
	INDEX IDX_StudentInfo_3 (studentname),
	INDEX IDX_StudentInfo_4 (phoneno),
	INDEX IDX_StudentInfo_5 (wechat ),
	INDEX IDX_StudentInfo_6 (email)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='学生信息登记表:';